# Use Rust docker image, see: https://hub.docker.com/_/rust/
image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
 
cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - cargo/
    - target/

# Defines stages which are to be executed
stages:
  - build
  - deploy-master

# Run `cargo test` for the project with stable Rust
run-build:
  stage: build
  image: rust:latest
  script:
    - rustc --version && cargo --version
    - cargo test

deploy-master:
  stage: deploy
  tags:
    - coward
  script:
    - cargo run --release
  environment:
    name: coward
  only:
    - master
